[global]
	server string = ksmbd selftest

[cifsd-test1]
	path = /mnt/test1
	read only = no
	guest ok = yes

[cifsd-test2]
	path = /mnt/test2
	read only = no
	guest ok = yes

[cifsd-test3]
	path = /mnt/test3
	read only = no
	guest ok = yes
